version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=beatbuddysearch
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=elasticsearch
    mem_limit: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./beatbuddysearch/:/usr/share/elasticsearch/data/

  kibana:
    image: library/kibana:8.12.2
    ports:
      - 5601:5601
