apiVersion: v1
kind: PersistentVolume
metadata:
  name: playlist-db-vol
  labels:
    uid: playlist-db-vol
spec:
  storageClassName: playlist-db-vol
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /database/playlist/