apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      uid: playlist-db-pod
  template:
    metadata:
      name: playlist-db-pod
      labels:
        uid: playlist-db-pod
    spec:
      volumes:
      - name: playlist-db-vol
        persistentVolumeClaim:
          claimName: playlist-db-volclaim
      containers:
      - name: playlist-db-cont
        image: bitnami/postgresql:16.2.0
        resources:
          limits:
            memory: "150M"
            cpu: "100m"
        ports:
          - containerPort: 5432
        envFrom:
          - secretRef:
              name: playlist-db-srt
          - configMapRef:
              name: playlist-db-cnfmap
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: playlist-db-vol
    