apiVersion: v1
kind: Secret
metadata:
  namespace: beatbuddy-ns
  name: catalog-srt
  labels:
    uid: catalog-srt
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vYmVhdGJ1ZGR5LWRiLWNsdXN0ZXItZG8tdXNlci0xNjA0OTM5MC0wLmMuZGIub25kaWdpdGFsb2NlYW4uY29tOjI1MDYwL2JlYXRidWRkeV9jYXRhbG9nP3NzbG1vZGU9cmVxdWlyZQ==
  SPRING_DATASOURCE_USERNAME: YmVhdGJ1ZGR5
  SPRING_DATASOURCE_PASSWORD: QVZOU19ONVVpakVrbVQ0aFB2NUxvWkZC
