apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist
  namespace: beatbuddy-ns
  labels:
    uid: playlist-dep
spec:
  selector:
    matchLabels:
      uid: playlist-pod
  template:
    metadata:
      labels:
        uid: playlist-pod
    spec:
      containers:
        - name: playlist-cont
          image: docker.io/vutiendat3601/beatbuddy-playlist-ms:1.0.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: 256Mi
              cpu: 400m
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: playlist-cnfmap
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: playlist-srt
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: playlist-srt
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: playlist-srt
                  key: SPRING_DATASOURCE_PASSWORD
