apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      uid: catalog-db-pod
  template:
    metadata:
      name: catalog-db-pod
      labels:
        uid: catalog-db-pod
    spec:
      volumeClaimTemplates:
      - metadata:
        name: catalog-db-volclaim
        spec:
          accessModes:
          - ReadWriteMany
          resources:
            requests:
              storage: 5Gi
          storageClassName: catalog-db-volclaim
      containers:
      - name: catalog-db-cont
        image: bitnami/postgresql:16.2.0
        resources:
          limits:
            memory: "150M"
            cpu: "100m"
        ports:
          - containerPort: 5432
        envFrom:
          - secretRef:
              name: catalog-db-srt
          - configMapRef:
              name: catalog-db-cnfmap
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: catalog-db-vol
    