apiVersion: v1
kind: PersistentVolume
metadata:
  name: catalog-db-vol
  labels:
    uid: catalog-db-vol
spec:
  storageClassName: catalog-db-vol
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /database/catalog/