name: beatbuddy
services:
  # eureka-discovery:
  #   image: docker.io/vutiendat3601/beatbuddy-eureka-discovery:1.0.0
  #   hostname: eureka-discovery
  #   environment:
  #     - SERVER_PORT=8000
  #     - EUREKA_INSTANCE_HOSTNAME=eureka-discovery
  #   networks:
  #     - default
  #   ports:
  #     - 8000:8000

  # nginx-gateway:
  #   image: docker.io/vutiendat3601/beatbuddy-nginx-gateway:1.0.0
  #   hostname: nginx-gateway
  #   environment:
  #     - GATEWAY_EUREKA_SERVER_URL=http://eureka-discovery:8000/eureka
  #     - GATEWAY_SERVICES=CATALOG,PLAYLIST
  #     - GATEWAY_REFRESH_SEC=3
  #   networks:
  #     - default
  #   ports:
  #     - 80:80
  
  # search-es:
  #   image: elasticsearch:8.12.2
  #   hostname: search-es
  #   environment:
  #     - node.name=search-es-1
  #     - cluster.name=search-es
  #     - bootstrap.memory_lock=true
  #     - cluster.initial_master_nodes=search-es-1
  #     - ES_JAVA_OPTS=-Xms1g -Xmx1g
  #   #mem_limit: 1g
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   volumes:
  #     - ./search-es/:/usr/share/elasticsearch/data/
  # catalog-db:
  #   image: docker.io/postgres:16.2-alpine3.19
  #   hostname: catalog-db
  #   environment:
  #     - POSTGRES_DB=beatbuddy_catalog
  #     - POSTGRES_USER=bbcatalogdb
  #     - POSTGRES_PASSWORD=bbcatalogdb
  #     - PGPASSWORD=bbcatalogdb
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - default
  #   volumes:
  #     - ./initdb.d/catalog/:/docker-entrypoint-initdb.d/
  # catalog-ms:
  #   image: docker.io/vutiendat3601/beatbuddy-catalog-ms:1.0.0
  #   hostname: catalog-ms
  #   environment:
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-discovery:8000/eureka
  #     - SERVER_PORT=8080
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://catalog-db:5432/beatbuddy_catalog
  #     - SPRING_DATASOURCE_USERNAME=bbcatalogdb
  #     - SPRING_DATASOURCE_PASSWORD=bbcatalogdb
  #     - SPRING_DOCKER_COMPOSE_ENABLED=false
  #   networks:
  #     - default

  # playlist-db:
  #   image: docker.io/postgres:16.2-alpine3.19
  #   hostname: playlist-db
  #   environment:
  #     - POSTGRES_DB=beatbuddy_playlist
  #     - POSTGRES_USER=bbplaylistdb
  #     - POSTGRES_PASSWORD=bbplaylistdb
  #     - PGPASSWORD=bbplaylistdb
  #   ports:
  #     - 5433:5432
  #   networks:
  #     - default
  #   # volumes:
  #   #   - :/docker-entrypoint-initdb.d/
  # playlist-ms:
  #   image: docker.io/vutiendat3601/beatbuddy-playlist-ms:1.0.0
  #   hostname: playlist-ms
  #   environment:
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-discovery:8000/eureka
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://playlist-db:5432/beatbuddy_playlist
  #     - SPRING_DATASOURCE_USERNAME=bbplaylistdb
  #     - SPRING_DATASOURCE_PASSWORD=bbplaylistdb
  #     - SPRING_DOCKER_COMPOSE_ENABLED=false
  #   networks:
  #     - default
  # playback-db:
  #   image: docker.io/postgres:16.2-alpine3.19
  #   hostname: playback-db
  #   environment:
  #     - POSTGRES_DB=beatbuddy_playback
  #     - POSTGRES_USER=bbplaybackdb
  #     - POSTGRES_PASSWORD=bbplaybackdb
  #     - PGPASSWORD=bbplaybackdb
  #   ports:
  #     - 5434:5432
  #   networks:
  #     - default
  #   # volumes:
  #   #   - ./initdb.d/playback/:/docker-entrypoint-initdb.d/
  
  javadev:
    image: mcr.microsoft.com/devcontainers/java:1-17-buster
    hostname: javadev
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ../:/workspace/beatbuddy:cached
      - ./vscode/:/home/vscode/
      - ./hosts:/etc/hosts
    networks:
      - default

networks:
  default:
    name: beatbuddy
    driver: bridge
