secretName: user-srt
configMapName: user-cnfmap
deploymentName: user-ms-dep
serviceName: user-ms
hostname: user-ms
appLabel: user-ms
appName: user-ms
containerPort: 8000
springCloudKubernetesDiscoveryEnabled: true

# # R2DBC configuration
r2dbcEnabled: true
springR2dbcUrl: r2dbc:postgresql://beatbuddy-sgp-pg-do-user-4169074-0.c.db.ondigitalocean.com:25060/beatbuddy_user?sslmode=require
springR2dbcUsername: beatbuddy
springR2dbcPassword: AVNS_elUMsgjoJ9M2Oxsavkh

# # Flyway configuration
flywayEnabled: true
springFlywayUrl: jdbc:postgresql://beatbuddy-sgp-pg-do-user-4169074-0.c.db.ondigitalocean.com:25060/beatbuddy_user?sslmode=require
springFlywayUser: beatbuddy
springFlywayPassword: AVNS_elUMsgjoJ9M2Oxsavkh
springFlywayBaselineVersion: 0
springFlywayBaselineOnMigrate: true

# # Kafka
kafkaEnabled: false

replicaCount: 1

image:
  repository: docker.io/vutiendat3601/beatbuddy-user-ms
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000
