secretName: playlist-srt
configMapName: playlist-cnfmap
deploymentName: playlist-ms-dep
serviceName: playlist-ms
hostname: playlist-ms
appLabel: playlist-ms
appName: playlist-ms
containerPort: 8020
springCloudKubernetesDiscoveryEnabled: true

# # R2DBC configuration
r2dbcEnabled: true
springR2dbcUrl: r2dbc:postgresql://beatbuddy-sgp-pg-do-user-4169074-0.c.db.ondigitalocean.com:25060/beatbuddy_playlist?sslmode=require
springR2dbcUsername: beatbuddy
springR2dbcPassword: AVNS_elUMsgjoJ9M2Oxsavkh

# # Flyway configuration
flywayEnabled: true
springFlywayUrl: jdbc:postgresql://beatbuddy-sgp-pg-do-user-4169074-0.c.db.ondigitalocean.com:25060/beatbuddy_playlist?sslmode=require
springFlywayUser: beatbuddy
springFlywayPassword: AVNS_elUMsgjoJ9M2Oxsavkh
springFlywayBaselineVersion: 0
springFlywayBaselineOnMigrate: true

# # Kafka
kafkaEnabled: false

replicaCount: 1

image:
  repository: docker.io/vutiendat3601/beatbuddy-playlist-ms
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 8020
  targetPort: 8020
