apiVersion: apps/v1
kind: Deployment
metadata:
  name: track
  namespace: beatbuddy-ns
  labels:
    uid: track-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      uid: track-pod
  template:
    metadata:
      labels:
        uid: track-pod
    spec:
      containers:
        - name: track-cont
          image: docker.io/vutiendat3601/beatbuddy-track-ms:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 256Mi
              cpu: 400m
          ports:
            - containerPort: 8050
          envFrom:
            - configMapRef:
                name: track-cnfmap
          env:
            - name: SPRING_R2DBC_URL
              valueFrom:
                secretKeyRef:
                  name: track-srt
                  key: SPRING_R2DBC_URL
            - name: SPRING_R2DBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: track-srt
                  key: SPRING_R2DBC_USERNAME
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: track-srt
                  key: SPRING_R2DBC_PASSWORD
            - name: SPRING_FLYWAY_URL
              valueFrom:
                secretKeyRef:
                  name: track-srt
                  key: SPRING_FLYWAY_URL
            - name: SPRING_FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: track-srt
                  key: SPRING_FLYWAY_USER
            - name: SPRING_FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: track-srt
                  key: SPRING_FLYWAY_PASSWORD
