spring:
  elasticsearch:
    connection-timeout: 30s
    username: elastic
    password: 123456Aa@
    uris: https://165.232.173.176:9200
logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            core: DEBUG